### ISSUE TITLE
Source  code of demo

### ISSUE THREAD

**Issue by XIGUATANG** [mgcrea/react-native-dnd#1]
I want to know the source code of the demo.

**Comment by mgcrea** [comment]
I've re-written the draggable grid from the ground up and I'm currently improving the docs.

There is now two easy-to-use components [`DraggableStack`](https://mgcrea.github.io/react-native-dnd/components/draggablestack/) and [`DraggableGrid`](https://mgcrea.github.io/react-native-dnd/components/draggablegrid/).

The draggable stack can only sort on a single axis but handles variable width. Probably what you want. I also have a `DraggableFlatList` in the works but there is still some issues when trying to sort out of bounds in specific situations.

I have added updated examples here:
https://github.com/mgcrea/react-native-dnd/tree/master/example/src/pages

Let me know if there is anything unclear.
