### ISSUE TITLE
Getting error on DndProvider methods

### ISSUE THREAD

**Issue by Rc85** [mgcrea/react-native-dnd#10]
If I invoke the on methods, I get [ReanimatedError: [Reanimated] Tried to synchronously call a non-worklet function on the UI thread.](https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting/#tried-to-synchronously-call-a-non-worklet-function-on-the-ui-thread)
```
<DndProvider onDragEnd={(e) => console.log('drag', e)} onBegin={(e) => console.log('begin', e)}>

</DndProvider>
```
If I don't invoke those method, no error.

**Comment by mgcrea** [comment]
These method must be flagged as worklet with the `"worklet"` tag since they run on the UI thread by default, you can still use `runOnJS` there if you need to run on the JS thread (eg. `setState`, etc.).

```

const onDragEnd = (e) => {
  "worklet";
  console.log('drag', e);
}

return <DndProvider onDragEnd={onDragEnd}>

</DndProvider>
```
