### ISSUE TITLE
Property '_worklet_init_data2' doesn't exist

### ISSUE THREAD

**Issue by amitchaudhary140** [mgcrea/react-native-dnd#13]
I have installed the library and I have been getting this error. I have expo managed project.

![image](https://github.com/mgcrea/react-native-dnd/assets/119692506/bc180b21-d979-44f0-aea4-b6ffa107b71d)

I am not sure if it has anything to do with this error:

ERROR  Error: [Reanimated] Mismatch between JavaScript part and native part of Reanimated (3.5.4 vs 3.3.0).
See `https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting#mismatch-between-javascript-part-and-native-part-of-reanimated` for more details., js engine: hermes

Because of the above error, I also downgraded the version to 3.3.0 but still the main issue persists. I even created new Expo project and tried, but same error.

**Comment by amitchaudhary140** [comment]
@mgcrea Any help is highly appreciated.

**Comment by Thomsr** [comment]
I have the same issue

**Comment by mgcrea** [comment]
Just encountered this as well on a new app, worked fine at first but failed at some point and did not manage to recover it. Looks like metro is having issues processing the built files at some point.

I did revert to the former simple build with tsc and everything should be working again now, just released the https://github.com/mgcrea/react-native-dnd/releases/tag/1.9.0

Hope it works for you as well.
