### ISSUE TITLE
How to specify draggable area of Draggable in DraggableStack?

### ISSUE THREAD

**Issue by fax1ty** [mgcrea/react-native-dnd#18]
I need to make a zone for which I can drag an item. How can this be done?
(So that I can drag items not over its entire width and height)

**Comment by mgcrea** [comment]
You might be able to use the new `shouldDropWorklet` prop from the `<DndProvider />` to achieve what you want. See https://github.com/mgcrea/react-native-dnd/blob/2.4.0/src/DndProvider.tsx#L63
