### ISSUE TITLE
FlatList use?

### ISSUE THREAD

**Issue by nextriot** [mgcrea/react-native-dnd#2]
Any plans to have an API for use with FlatList?

**Comment by mgcrea** [comment]
I've landed an initial implementation of a `<DraggableFlatlist />` in the [1.7.0 release](https://github.com/mgcrea/react-native-dnd/releases/tag/1.7.0).

Here is an usage example:
https://github.com/mgcrea/react-native-dnd/blob/master/example/src/FlatListExample.tsx

![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-09-12 at 16 53 41](https://github.com/mgcrea/react-native-dnd/assets/108273/53b7870d-52fb-402e-88c7-cae7b715bcca)

The current over scroll is a bit messy and I'm looking into ways to improve it.

Feel free to open new issues regarding the current implementation!
