### ISSUE TITLE
Add collision detection algorithms

### ISSUE THREAD

**Issue by utanashati** [mgcrea/react-native-dnd#28]
First of all, thank you for a handy dnd tool for React Native!

Coming from dnd-kit for React, I'm missing being able to choose how [collision detection](https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/core-droppable-usedroppable--collision-detection-algorithms) happens. 

As far as I see it implemented in the `DndProvider`, one possibility would be to add an optional prop function to the `DndProvider` with `activeLayout` and `layouts` props to enable devs to write their own collision detection algorithms. 

The other one would be to write a few variants inside the DndProvider and add a prop that would allow to choose one of them. 

I personally like the "rect intersection" from dnd-kit more than checking whether the left top corner of a draggable is within a droppable.

@mgcrea What do you think?

**Comment by mgcrea** [comment]
I have added a `shouldDropWorklet` prop to the `<DndProvider />`, that you can use to customise the collision logic for droppable elements.

Here are a few collision methods you can use in place of the default one which is when the center of the draggable overlaps a droppable element.

https://github.com/mgcrea/react-native-dnd/blob/master/src/utils/collision.ts
