### ISSUE TITLE
Not working with tab navigation on android

### ISSUE THREAD

**Issue by devirtua** [mgcrea/react-native-dnd#31]
Hi,

I am using `react-native-dnd` alongside `@react-navigation/material-top-tabs`. I’ve encountered an issue where if multiple screens in the tab navigator contain draggable components from `react-native-dnd`, only one of the screens allows dragging.
It exhibits the same behavior in both Expo and bare projects.

This issue occurs only on Android. There are no problems on iOS or the web.

You can find MRE for this issue here: [Snack - Tab DND](https://snack.expo.dev/@kadirsevil/tab-dnd).

**Comment by mgcrea** [comment]
Unfortunately I don't think there is anything we can do to fix it at this level. You might want to create a ticket on the react-native-gesture-handler repo since I guess the issue might be fixed there.
