### ISSUE TITLE
Reanimated versions mismatch

### ISSUE THREAD

**Issue by shevy0** [mgcrea/react-native-dnd#4]
Hello, I have reanimated 3.3.0 installed in my project, but when I'm trying to execute your code I'm getting an error saying there is a Reanimated version mismatch (3.3.0 vs 3.1.0 in your library).

**Comment by mgcrea** [comment]
Just released the [v1.3.1](https://github.com/mgcrea/react-native-dnd/releases/tag/1.3.1) that should address the version mismatch error. Thanks for reporting the issue!
