### ISSUE TITLE
Activate drag after long press?

### ISSUE THREAD

**Issue by shevy0** [mgcrea/react-native-dnd#5]
Hi, is there any way to activate dragging after long press on the draggable item?

**Comment by mgcrea** [comment]
Hi, I've just released a new version that supports both activationDelay / minDistance configuration globally on the `<DndProvider />` or on individual draggable items (currently activationDelay / activationTolerance) either via `useDraggable()` or the `<Draggable />` component).

Released in [1.4.0](https://github.com/mgcrea/react-native-dnd/releases/tag/1.4.0)
