### ISSUE TITLE
Reanimated mismatch error

### ISSUE THREAD

**Issue by bytewiz** [mgcrea/react-native-dnd#8]
<img width="392" alt="image" src="https://github.com/mgcrea/react-native-dnd/assets/16811871/33ac9890-32ac-467b-8137-17af0fb63f8f">

I am running this with Expo using the prebuilds
#4 I am experiencing a similar error with react-native-reanimated.

```
    "@mgcrea/react-native-dnd": "^1.5.8",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-haptic-feedback": "^2.0.3",
    "react-native-reanimated": "~3.3.0",
    ```

Any clue what this might be?

**Comment by mgcrea** [comment]
This should be fixed with the latest `1.6.1` release, please retry :)
